name: daesim
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - importlib_metadata
  - ipython
  - jupyter
  - jupytext
  - nb_black
  - notebook
  - pip
  - pip:
    - -r requirements.txt