name: daesim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - importlib_metadata
  - ipython
  - jupyter
  - jupytext
  - matplotlib>=2.2.5
  - nb_black
  - notebook
  - pandas>=1.4.4
  - pip
  - pip:
    - -r requirements.txt
  - scipy>=1.9.1
